### ISSUE TITLE
not able to run standalone server and download script is not working either

### ISSUE THREAD

**Issue by sharmaraju352** [limcheekin/open-text-embeddings#14]
(vllm-custom) root@llamatest:~/vllm/open-text-embeddings# MODEL=intfloat/e5-large-v2 VERBOSE=1 python -m open.text.embeddings.server
Using device: cuda
Loading model: intfloat/e5-large-v2
Normalize embeddings: True
Traceback (most recent call last):
  File "/root/anaconda3/envs/vllm-custom/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/vllm-custom/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/vllm/open-text-embeddings/open/text/embeddings/server/__main__.py", line 22, in <module>
    app = create_app()
  File "/root/vllm/open-text-embeddings/open/text/embeddings/server/app.py", line 27, in create_app
    initialize_embeddings()
  File "/root/vllm/open-text-embeddings/open/text/embeddings/server/app.py", line 121, in initialize_embeddings
    embeddings = HuggingFaceInstructEmbeddings(model_name=model_name,
  File "/root/anaconda3/envs/vllm-custom/lib/python3.9/site-packages/langchain_community/embeddings/huggingface.py", line 153, in __init__
    self.client = INSTRUCTOR(
  File "/root/anaconda3/envs/vllm-custom/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 190, in __init__
    modules = self._load_sbert_model(
TypeError: _load_sbert_model() got an unexpected keyword argument 'token'
(vllm-custom) root@llamatest:~/vllm/open-text-embeddings# pip show open-text-embeddings
Name: open-text-embeddings
Version: 1.0.4
Summary: Open Source Text Embedding Models with OpenAI API-Compatible Endpoint
Home-page: https://github.com/limcheekin/open-text-embeddings
Author: Lim Chee Kin
Author-email: limcheekin@vobject.com
License: MIT
Location: /root/anaconda3/envs/vllm-custom/lib/python3.9/site-packages
Requires: langchain
Required-by:
(vllm-custom) root@llamatest:~/vllm/open-text-embeddings# pip show openai
Name: openai
Version: 1.13.3
Summary: The official Python library for the openai API
Home-page:
Author:
Author-email: OpenAI <support@openai.com>
License:
Location: /root/anaconda3/envs/vllm-custom/lib/python3.9/site-packages
Requires: anyio, distro, httpx, pydantic, sniffio, tqdm, typing-extensions
Required-by:
(vllm-custom) root@llamatest:~/vllm/open-text-embeddings#

Download script is also not working
(vllm-custom) root@llamatest:~/vllm/open-text-embeddings# ./download.sh intfloat/e5-large-v2
mkdir: missing operand
Try 'mkdir --help' for more information.
Updated git hooks.
Git LFS initialized.
Cloning into 'huggingface.co'...
fatal: repository 'https://huggingface.co/' not found
Not in a git repository.
Git LFS initialized.
/root
total 2672
(vllm-custom) root@llamatest:~/vllm/open-text-embeddings#

**Comment by limcheekin** [comment]
Thanks for report the issue. 

Please pull the latest code and re-test it.

If it works, please close the issue. Thanks.

**Comment by limcheekin** [comment]
@sharmaraju352 close the issue for now, please re-open if the issue persist.
